### ISSUE TITLE
Where is the training process of the pre-training segmentation model?

### ISSUE THREAD

**Issue by LittleMinXiao** [cai-mj/UMA#1]
Hello, I have read your article. Your work is very good and inspires me a lot. When I read the code on GitHub, I did not find the training process of the pre-trained segmentation model (bayes_rf101_egTEA_00040. PTH. Tar), can you eliminate my doubt?

**Comment by cai-mj** [comment]
@LittleMinXiao I have updated the github to add a file for generating the pre-trained segmentation model. Please see readme.
